In [1]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv("./play_tennis.csv")
data.drop(columns=["day"], inplace=True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [ ]:
data["humidity"].unique()

array(['High', 'Normal'], dtype=object)

In [ ]:
# Problem : Outlook=Sunny, Temp=Hot, Humidity=Hight, Wind=Weak
# Predict: Play = Yes/No

(14, 5)

In [ ]:
data["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
py, px = 9 / 14, 5 / 14

In [ ]:
pd.crosstab(data["outlook"], data["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [10]:
Pon, Prn, Psn = 0, 2 / 5, 3 / 5
Poy, Pry, Psy = 4 / 9, 3 / 9, 2 / 9