In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("./titanic.csv")

In [5]:
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [ ]:
df["number"].value_counts()

number
A    139
6    131
1    129
2    126
4    126
5    123
3    117
Name: count, dtype: int64

In [ ]:
df["number_numerical"] = pd.to_numeric(
    df["number"], errors="coerce", downcast="integer"
)


df["number_categorical"] = np.where(
    df["number_numerical"].isnull(), df["number"], np.nan
)

df["number_numerical"][df["number_numerical"] == np.nan]

Series([], Name: number_numerical, dtype: float64)

In [ ]:
df["cabin_num"] = df["Cabin"].str.extract("(\d+)")  # captures numerical part
df["cabin_cat"] = df["Cabin"].str[0]  # captures first letter

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_225452/3921628339.py:1: SyntaxWarning: invalid escape sequence '\d'
  df["cabin_num"] = df["Cabin"].str.extract('(\d+)')  # captures numerical part

In [18]:
df.head()

,Cabin,Ticket,number,Survived,number_numerical,number_categorical,cabin_num,cabin_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN