In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import statsmodels.api as sm

from statsmodels.stats.outliers_influence import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm

In [ ]:
from ISLP import load_data
from ISLP.models import ModelSpec as MS, summarize, poly

In [4]:
dir()

['In',
 'MS',
 'Out',
 'VIF',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_i4',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'anova_lm',
 'exit',
 'get_ipython',
 'load_data',
 'np',
 'open',
 'pd',
 'plt',
 'poly',
 'quit',
 'sm',
 'summarize']

### 3.6.2 Simple Linear Regression

In [8]:
df = load_data("Boston")

df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,5.33,36.2

In [11]:
X = pd.DataFrame({"intercept": np.ones(df.shape[0]), "lstat": df["lstat"]})

X

     intercept  lstat
0          1.0   4.98
1          1.0   9.14
2          1.0   4.03
3          1.0   2.94
4          1.0   5.33
..         ...    ...
501        1.0   9.67
502        1.0   9.08
503        1.0   5.64
504        1.0   6.48
505        1.0   7.88

[506 rows x 2 columns]

In [ ]:
y = df["medv"]
model = sm.OLS(y, X)
results = model.fit()

In [16]:
summarize(results)

              coef  std err       t  P>|t|
intercept  34.5538    0.563  61.415    0.0
lstat      -0.9500    0.039 -24.528    0.0