In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("./Week1_GA_dataset.csv")

In [12]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [13]:
df.shape

(10000, 12)

---
#### Question 1

In [14]:
even_rows = df.iloc[::2]
even_rows.iloc[0,3]

111440.0

---
#### Question 2

In [15]:
even_rows.iloc[332,3]

256200.0

---
#### Question 3

In [17]:
odd_rows = df.iloc[1::2]
odd_rows.iloc[332,3]

352940.0

In [18]:
odd_rows.iloc[100,5]

'Single Family'

In [19]:
even_row_col = df.iloc[::2, ::2]
even_row_col.iloc[255,3]

'Detached House'

---
#### Question 6

In [22]:
recent_six_years = df["Year"].dropna().sort_values(ascending=False).unique()[:6]
print(recent_six_years)

print("Count: ", df[df["Year"].isin(recent_six_years)].shape[0])

[2022 2021 2020 2019 2018 2017]
Count:  4749

---
#### Question 7

In [ ]:
df[(df['num_rooms'] ==3 )& (df['num_bathrooms'] == 3)].shape[0]

2730

---
#### Question 8

In [29]:
df[(df['num_rooms'] ==3 ) | (df['num_bathrooms'] == 3)].shape[0]

8591

---
#### Question 9

In [34]:
df[
    (df['Year'] == 2022) &
    (df['Locality'] == "Greenwich") &
    (df['num_rooms'] == 3) &
    (df['Face'].isin(['North', 'East']))
].shape[0]

42

---
### Question 10

In [39]:
df['Date'] = pd.to_datetime(df["Date"], errors='coerce')
df.head(2)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South

In [41]:
(df['Date'].dt.month == 8).sum()

1050

---
### Question 11

In [45]:
avg_price = df.groupby("Locality")["Sale Price"].mean()
top_locality = avg_price.idxmax()

print(top_locality, avg_price.max())

Greenwich 2270223.539495238