#### Lec 1,2 Pandas Series & Dataframe | Part 1,2

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [3]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes(as_frame=True)
df = diabetes['data']

### sklearn.Bunch
- Bunch objects are sometimes used as an output for functions and methods.
- They extend dictionaries by enabling values to be accessed by key, bunch\["value_key"\],
 or by an attribute, bunch.value_key.

In [4]:
type(diabetes)

sklearn.utils._bunch.Bunch

In [5]:
food_items = pd.Series(['Paneer', 'Chicken', 'Soya'])
protein_content = pd.Series([20.0, 30.0, 50.0])

protein_info_df = pd.DataFrame({"Food" : food_items, "Protein Content" : protein_content})
protein_info_df

      Food  Protein Content
0   Paneer             20.0
1  Chicken             30.0
2     Soya             50.0

---

In [6]:
df.shape

(442, 10)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

In [8]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

---
#### Lec-3 Data Selection using Pandas | PT 1

In [9]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

##### `df.iloc vs df.loc`

In [12]:
df.iloc[0, 0:3]

age    0.038076
sex    0.050680
bmi    0.061696
Name: 0, dtype: float64

In [14]:
df.loc[0, ['age', 'bmi']]

age    0.038076
bmi    0.061696
Name: 0, dtype: float64

----
#### Lec - 4 Data Selection using Pandas | PT 2

In [22]:
import numpy as np

In [34]:
df_num = pd.DataFrame(np.random.rand(100,4)*100, index=range(100), columns=list("ABCD"))
df_num.head()

           A          B          C          D
0  44.826032  25.714268  58.438630  10.413913
1  79.594406   7.990444  74.221749  69.388483
2  36.504948  42.747420  79.596037  70.654410
3  95.867261  88.280092  63.280859  32.351211
4  38.078452  96.250996  86.893762  57.083576

In [32]:
selector = lambda df_num: df_num['B'] > 90.0

In [33]:
df_num.loc[selector]

            A          B          C          D
3   44.716601  98.976572  34.749358  68.914889
14  94.089559  97.188054  92.583110  44.583963
22  69.520088  99.839686  14.867099  66.455569
23  63.218696  94.846259  55.946510  36.883069
26  55.819860  98.389016  63.045625   0.390551
38  51.321744  94.627470  84.227093   1.275766
40  25.351680  96.996458  68.581409  66.824233
48  92.341453  94.560995  11.473018  70.268766
79  17.013448  96.529297   0.344029  37.996634
85  61.390383  99.388163  63.995890  63.729794

---
### Lec-5 Drop in DataFrame

In [35]:
df_copy = df_num.copy()

In [39]:
df_copy.drop(columns=['A'])
df_copy

            A          B          C          D
0   44.826032  25.714268  58.438630  10.413913
1   79.594406   7.990444  74.221749  69.388483
2   36.504948  42.747420  79.596037  70.654410
3   95.867261  88.280092  63.280859  32.351211
4   38.078452  96.250996  86.893762  57.083576
..        ...        ...        ...        ...
95   5.793028  38.074194  22.836467  82.792087
96  33.886373  50.874579   4.610794  78.678525
97  16.689644  89.348664  30.134734  61.945703
98  38.585310  98.571024  60.874561  83.922731
99  42.582352  82.926380  23.970419  85.170658

[100 rows x 4 columns]

---
#### Lec-6 Apply statistics using Pandas